# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "which_works"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["AlphaHydrae"]
  s.date = "2013-09-10"
  s.description = "Locates a program file in the user's path. The which method takes a list of command names and searches the path for each executable file that would be run had these commands actually been invoked."
  s.email = "hydrae.alpha@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/which_works.rb"
  ]
  s.homepage = "https://github.com/AlphaHydrae/which_works"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Ruby UNIX-like which."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, ["~> 10.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<shoulda>, ["~> 3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.0"])
      s.add_development_dependency(%q<rdiscount>, ["~> 1.0"])
      s.add_development_dependency(%q<travis-lint>, ["~> 1.0"])
      s.add_development_dependency(%q<rake-version>, ["~> 0.0"])
    else
      s.add_dependency(%q<rake>, ["~> 10.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<shoulda>, ["~> 3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.0"])
      s.add_dependency(%q<yard>, ["~> 0.0"])
      s.add_dependency(%q<rdiscount>, ["~> 1.0"])
      s.add_dependency(%q<travis-lint>, ["~> 1.0"])
      s.add_dependency(%q<rake-version>, ["~> 0.0"])
    end
  else
    s.add_dependency(%q<rake>, ["~> 10.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<shoulda>, ["~> 3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.0"])
    s.add_dependency(%q<yard>, ["~> 0.0"])
    s.add_dependency(%q<rdiscount>, ["~> 1.0"])
    s.add_dependency(%q<travis-lint>, ["~> 1.0"])
    s.add_dependency(%q<rake-version>, ["~> 0.0"])
  end
end

